# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 5 --min_session_length 5 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path roberta-base
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 6 --min_session_length 6 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path roberta-base
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 7 --min_session_length 7 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path roberta-base
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 5 --min_session_length 5 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path mlm_modeling/runs/bert_base_cased_512bs/checkpoint-2500
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 6 --min_session_length 6 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path mlm_modeling/runs/bert_base_cased_512bs/checkpoint-2500
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 7 --min_session_length 7 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path mlm_modeling/runs/bert_base_cased_512bs/checkpoint-2500
# python train.py --accumulate_grad_batches 4 --train_batch_size 8 --gpu 1 --max_session_length 5 --min_session_length 5 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path albert-xxlarge-v2  
# python train.py --accumulate_grad_batches 4 --train_batch_size 8 --gpu 1 --max_session_length 6 --min_session_length 6 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path albert-xxlarge-v2  
# python train.py --accumulate_grad_batches 4 --train_batch_size 8 --gpu 1 --max_session_length 7 --min_session_length 7 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path albert-xxlarge-v2  

# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 4 --min_session_length 4 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 0 --model_type GRU --learning_rate 1e-3 --max_epochs 100 --limit_n_train_data 10
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 5 --min_session_length 5 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 0 --model_type GRU --learning_rate 1e-3 --max_epochs 100 --limit_n_train_data 10
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 6 --min_session_length 6 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 0 --model_type GRU --learning_rate 1e-3 --max_epochs 100 --limit_n_train_data 10
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 4 --min_session_length 4 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 100 --limit_n_train_data 10 --loss_type 'cross-entropy'    
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 5 --min_session_length 5 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 100 --limit_n_train_data 10 --loss_type 'cross-entropy'    
# python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 6 --min_session_length 6 --data_dir 'datasets/MovieLens-1M-5Star' --max_seq_length 128 --max_epochs 100 --limit_n_train_data 10 --loss_type 'cross-entropy'    


python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 4 --min_session_length 4 --data_dir 'datasets/MovieTweet' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path roberta-base
python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 7 --min_session_length 4 --data_dir 'datasets/MovieTweet' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path roberta-base
python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 5 --min_session_length 4 --data_dir 'datasets/MovieTweet' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path roberta-base
python train.py --accumulate_grad_batches 1 --train_batch_size 32 --gpu 1 --max_session_length 6 --min_session_length 4 --data_dir 'datasets/MovieTweet' --max_seq_length 128 --max_epochs 20 --loss_type 'cross-entropy' --model_name_or_path roberta-base
